### ISSUE TITLE
ZBDongle-E reset loop after firmware upgrade

### ISSUE THREAD

**Issue by Gl4di470r** [itead/Sonoff_Zigbee_Dongle_Firmware#12]
Hi,

I've updated my Dongle-E with the latest router firmware (Z3RouterUSBDonlge_EZNet6.10.3_V1.0.0) after reboot I get only the following messages in loop.
Extended Reset info: 0x0401 (HV )

[ASSERT:C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/platform/base/hal/micro/cortexm3/efm32/token.c:211]
Reset info: 0x07 (CRS)
Extended Reset info: 0x0701 (AST)
Thread mode using main stack (20002460 to 20002DC0), SP = 20002CF0
640 bytes used (27%) in main stack (out of 2400 bytes total)
No interrupts active
Reset cause: Assert C:/SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/platform/base/hal/micro/cortexm3/efm32/token.c:211
R0 = 0004421A, R1 = 000000D3, R2 = 2000302C, R3 = 00000001
R4 = 00000000, R5 = 00000000, R6 = 0000000E, R7 = 00000031
R8 = 200033D4, R9 = 00041900, R10 = 000417D8, R11 = 200033D4
R12 = 00000001, R13(LR) = FFFFFFF9, MSP = 20002CF0, PSP = 20002DC0
PC = 00008314, xPSR = 69100000, MSP used = 00000280, PSP used = 00000000
CSTACK bottom = 20002460, ICSR = 00000806, SHCSR = 00070008, INT_ACTIVE0 = 00000000
INT_ACTIVE1 = 00000000, CFSR = 00010000, HFSR = 00000000, DFSR = 00000000
MMAR/BFAR = E000ED34, AFSR = 00000000, Ret0 = 00013A95, Ret1 = 0000833B
Ret2 = 0000958B, Ret3 = 00024263, Ret4 = 0002CA0B, Ret5 = 00015199
Dat0 = 0004421A, Dat1 = 000000D3

Is there anyway to fix it?

Thanks

**Comment by drifton** [comment]
Hey, did you somehow resolve this?

**Comment by Gl4di470r** [comment]
> Hey, did you somehow resolve this?

Hi, no I don't have a fix for this issue. The problem is that I upgraded the stick with a EZSP v9 firmware that modified the token in the NVM. Therefore, the downgraded v8 router firmware doesn't work. It seems downgrade is not supported, so at the moment the only way to use the stick is EZSP v9 coordinator.

**Comment by Gl4di470r** [comment]
> Hey, did you somehow resolve this?

Hi, no I don't have a fix for this issue. The problem is that I upgraded the stick with a EZSP v9 firmware that modified the token in the NVM. Therefore, the downgraded v8 router firmware doesn't work. It seems downgrade is not supported, so at the moment the only way to use the stick is EZSP v9 coordinator.

**Comment by Gl4di470r** [comment]
> Hey, did you somehow resolve this?

Hi, no I don't have a fix for this issue. The problem is that I upgraded the stick with a EZSP v9 firmware that modified the token in the NVM. Therefore, the downgraded v8 router firmware doesn't work. It seems downgrade is not supported, so at the moment the only way to use the stick is EZSP v9 coordinator.
